//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTIWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegId { get; set; }
        public string Username { get; set; }
        public string Pwd { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
    }
}
